module.exports = {
  TIME_TO_SCHEDULE_GAME_NOTIFICATIONS: 1000 * 10, // ms
  BOT_ENDPOINT: `/secret-path`,
  UPDATE_NOTIFICATIONS_CRON_SCHEDULE: `*/1 * * * *`,
  GAME_NOTIFICATIONS_CRON_SCHEDULE: `*/10 * * * * *`,
}
